fos_ck_editor:
    default_config: default
    configs:
        default:
            toolbar: [ 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote' ]
            uiColor: '#ffffff'
