# config/packages/hwi_oauth.yaml

hwi_oauth:
    resource_owners:
        any_name:
            type:                google
            client_id:           917500631875-c9p0np8212pk2pq2aum4af3ll1hjjev0.apps.googleusercontent.com
            client_secret:       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
            scope:               "email profile"