vich_uploader:
    db_driver: orm

    mappings:
       articles:
           uri_prefix: /images/articles
           upload_destination: '%kernel.project_dir%/public/images/articles'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       audio:
           uri_prefix: /images/audio
           upload_destination: '%kernel.project_dir%/public/images/audios'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           
       acover:
           uri_prefix: /images/acover
           upload_destination: '%kernel.project_dir%/public/images/acover'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true